CREATE DATABASE CAFEDB;

USE CAFEDB;

CREATE TABLE CUSTOMERS(
	CUSTCUID INT PRIMARY KEY AUTO_INCREMENT,
    CUSTNAME VARCHAR(255) NOT NULL,
    CUSTPHNO VARCHAR(10) NOT NULL,
    CUSTMAIL VARCHAR(255)
    );

DROP TABLE MENU;

CREATE TABLE MENU(
	ITEMIUID INT PRIMARY KEY AUTO_INCREMENT,
	ITEMNAME VARCHAR(255) NOT NULL,
    ITEMPRIC INT NOT NULL,
    ITEMTYPE INT,
    ITEMTXTP INT,
    ITEMAVAIL BOOLEAN NOT NULL,
    FOREIGN KEY (ITEMTYPE) REFERENCES ITEMTYPE(ITTPIUID)
    );

CREATE TABLE ITEMTYPE (
    ITTPIUID INT PRIMARY KEY AUTO_INCREMENT,
    ITTPTYPE VARCHAR(255) NOT NULL,
    ITTPSBTP VARCHAR(255) NOT NULL
);


CREATE TABLE ORDERS(
	ORDRPKID INT PRIMARY KEY AUTO_INCREMENT,
	ORDROUID INT,
    ORDRCUID INT,
    ORDRIUID INT,
    ORDRPRIC DOUBLE NOT NULL,
    ORDRQNTY INT NOT NULL,
    ORDRTTAX DOUBLE NOT NULL,
    ORDRTOTL DOUBLE NOT NULL,
    ORDRDELV BOOLEAN NOT NULL,
    ORDRDISC DOUBLE,
    ORDRRFND DOUBLE,
    ORDRTIME datetime,
	FOREIGN KEY (ORDRCUID) REFERENCES CUSTOMERS(CUSTCUID),
	FOREIGN KEY (ORDRIUID) REFERENCES MENU(ITEMIUID)
    );

use cafedb;
CREATE TABLE EXCEPTION_DETAILS(
	EXCPEUID INT PRIMARY KEY auto_increment,
    EXCPTIME datetime,
    EXCPMESG varchar(500),
    EXCPDETL VARCHAR(255)   
);

DROP TABLE EXCEPTION_DETAILS;
ALTER TABLE EXCEPTIONDETAILS RENAME TO EXCEPTION_DETAILS;

select * from EXCEPTION_DETAILS;
    
SHOW TABLES;
    
SELECT * FROM MENU;
DELETE FROM menu;

SHOW GLOBAL VARIABLES LIKE 'local_infile';
SET GLOBAL local_infile = TRUE;

LOAD DATA LOCAL INFILE 'D:/Projects/CafeShopBackend/CUSTOMER_DATA.csv' INTO TABLE CUSTOMERS
  FIELDS TERMINATED BY ',' ENCLOSED BY '"'
  LINES TERMINATED BY '\r\n'
  IGNORE 1 LINES
  (CUSTNAME,CUSTPHNO,CUSTMAIL);
  


LOAD DATA LOCAL INFILE 'D:/Projects/CafeShopBackend/ITEMTYPE.csv' INTO TABLE ITEMTYPE
  FIELDS TERMINATED BY ',' ENCLOSED BY '"'
  LINES TERMINATED BY '\r\n'
  IGNORE 1 LINES
  (ITTPTYPE,ITTPSBTP);
  
LOAD DATA LOCAL INFILE 'D:/Projects/CafeShopBackend/MENU.csv' INTO TABLE MENU
  FIELDS TERMINATED BY ',' ENCLOSED BY '"'
  LINES TERMINATED BY '\r\n'
  IGNORE 1 LINES
  (ITEMNAME,ITEMPRIC,ITEMTYPE,ITEMTXTP,ITEMAVAIL);
  
  LOAD DATA LOCAL INFILE 'D:/Projects/CafeShopBackend/MENU.csv' INTO TABLE MENU
  FIELDS TERMINATED BY ',' ENCLOSED BY '"'
  LINES TERMINATED BY '\r\n'
  IGNORE 1 LINES
  (ITEMNAME,ITEMPRIC,ITEMTYPE,ITEMTXTP,ITEMAVAIL);
  
SELECT *
FROM MENU
INNER JOIN ITEMTYPE ON MENU.ITEMTYPE=ITEMTYPE.ITTPIUID ORDER BY MENU.ITEMNAME;